name: Update Economic Data

on:
  schedule:
    - cron: "0 22 * * *" # Executa às 22h UTC diariamente
  workflow_dispatch: # Permite execução manual

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datetime dateutil google.colab urllib.parse time requests pandas numpy os

      - name: Colect script execution
        run: python /scripts/fred_script.py
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}

      - name: Commit and push of the new file
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add database.xlsx
          git commit -m "Atualização automática de dados [skip ci]" || echo "No changes"
          git push
